shop_main_homepage:
    path:     /
    defaults: { _controller: ShopMainBundle:Default:index }


shop_main_current_user:
    path:     /current_user
    defaults: { _controller: ShopMainBundle:User:index }

shop_main_current_user_cart:
    path:     /current_user/cart
    defaults: { _controller: ShopMainBundle:User:cart }

shop_main_current_user_addToCart:
    path:     /current_user/add_to_cart/{id}
    defaults: { _controller: ShopMainBundle:User:addToCart }





shop_main_movies:
    path: /movies
    defaults:
        _controller: ShopMainBundle:Movie:index

shop_main_movies_create:
    path: /movies/create
    defaults:
        _controller: ShopMainBundle:Movie:create

shop_main_movies_edit:
    path: /movies/{id}/edit
    defaults:
        _controller: ShopMainBundle:Movie:edit

shop_main_movies_delete:
    path: /movies/{id}/delete
    defaults:
        _controller: ShopMainBundle:Movie:delete

shop_main_movies_details:
    path: /movies/{id}/details
    defaults:
        _controller: ShopMainBundle:Movie:details





shop_main_categories:
        path: /categories
        defaults:
            _controller: ShopMainBundle:Category:index

shop_main_categories_create:
        path: /categories/create
        defaults:
            _controller: ShopMainBundle:Category:create

shop_main_categories_edit:
        path: /categories/{id}/edit
        defaults:
            _controller: ShopMainBundle:Category:edit






shop_main_actors:
       path: /actors
       defaults:
           _controller: ShopMainBundle:Actor:index

shop_main_actors_create:
       path: /actors/create
       defaults:
           _controller: ShopMainBundle:Actor:create

shop_main_actors_edit:
       path: /actors/{id}/edit
       defaults:
           _controller: ShopMainBundle:Actor:edit





shop_main_reviews:
      path: /reviews
      defaults:
          _controller: ShopMainBundle:Review:index

shop_main_reviews_create:
      path: /reviews/create
      defaults:
          _controller: ShopMainBundle:Review:create



shop_main_orders:
      path: /orders
      defaults:
          _controller: ShopMainBundle:Order:index

shop_main_orders_create:
      path: /orders/create
      defaults:
          _controller: ShopMainBundle:Order:create