shop_main_homepage:
    path:     /
    defaults: { _controller: ShopMainBundle:Default:index }

shop_main_movies_create:
    path: /movies/create
    defaults:
        _controller: ShopMainBundle:Movie:create

shop_main_tag_create:
    path: /tags/create
    defaults:
        _controller: ShopMainBundle:Tag:create

shop_main_movies_index:
    path: /movies/{index}
    defaults:
        _controller: ShopMainBundle:Movie:index