services:
#    jkanclerz_demo.example:
#        class: Jkanclerz\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#    jkanclerz_name_provider:
#        class: Jkanclerz\Component\Name\NameProvider
#        arguments: [@session]
    a_piszczek_demo.listener:
        class: Shop\MainBundle\Entity\Movie
        tags:
            - { name: doctrine.event_listener, event: postInsert, connection: default  }
            - { name: doctrine.event_listener, event: preInsert, connection: default  }
