services:
    shop_name_provider:
        class: Shop\MainBundle\Component\Name\NameProvider
        arguments: [@session]
    shop_main.listener:
        class: Shop\MainBundle\Entity\Movie
        tags:
            - { name: doctrine.event_listener, event: postInsert, connection: default  }
            - { name: doctrine.event_listener, event: preInsert, connection: default  }
